### ISSUE TITLE
CI doesn't build website

### ISSUE THREAD

**Issue by ben9583** [64bitpandas/catan#2]
So it looks like from the latest deployment that the Github Action setup to deploy the website isn't doing an `npm run build` but instead just taking the code as is and using it as the static website. The problem with this is that imports/exports are being used and so the javascript has to be bundled using `npm run build`.

I don't have access to the Github Actions configuration, but basically it needs to be updated to use Node instead of Jekyll, run `npm i && npm run build`, and upload `dist/` as the artifact instead.

Sorry for the trouble! I didn't catch that the CI wasn't doing that earlier during the PR.

**Comment by 64bitpandas** [comment]
i'll switch it over to netlify tonight!

**Comment by 64bitpandas** [comment]
fixed! github pages is no more
